### PR TITLE
Fix/summary labels and sectionhome summary

### LINKED ISSUE #258: Short summary and sectionhomes aka landing pages
I’ve noticed the sectionhomes aka landing pages in the CMS don’t have the ‘short summary’ field which means that authors would be forced to place their short summaries inside the body text area (and potentially miss the styling associated with the short summary field).

At this stage I can't see an argument for a sectionhome aka landing page having a summary (aka long summary) field, but so far all minister and department landing pages definitely need short summaries visible to users.

### PR DESCRIPTION
**Pull request by ltankey**
Fixes #258 and #259.

### CODE REVIEW

File: spec/controllers/news_controller_spec.rb [hunk 1]
```diff
@@ -52,9 +54,9 @@
         expect(assigns(:articles)).to_not include(article_unpub)
       end
 
-      it 'should return a list ordered by date and name' do
-        expect(assigns(:articles).to_a).to eq([article_today_c, article_today_a, article_today_b, article_yesterday])
-      end
+     it 'should return a list ordered by date and name' do
+       expect(assigns(:articles).to_a).to eq([article_today_c, article_today_a, article_today_b, article_yesterday])
+     end
```
Comment (tessereth) [inline spec/controllers/news_controller_spec.rb]: I think the indenting here was originally correct and is now one space too short.

**Comment by ltankey** [comment]
Fixed!

File: spec/controllers/news_controller_spec.rb (hunk 1 above)
Comment (ltankey) [inline spec/controllers/news_controller_spec.rb]: Fixed!

File: app/views/editorial/submissions/_section_home.html.haml [hunk 2]
```diff
@@ -0,0 +1 @@
+= f.input :short_summary
```
Comment (tessereth) [inline app/views/editorial/submissions/_section_home.html.haml]: Is short_summary an attribute of Node? If so, should the form entry be in `new.html.haml` rather than the subclass specific partials?

Comment (ltankey) [inline app/views/editorial/submissions/_section_home.html.haml]: Good point, I've moved it into the new.html.haml file.

**Comment by maxious** [comment]
LGTM

**Comment by tessereth** [comment]
LGTM
